### ISSUE TITLE
Implement new music description format

### ISSUE THREAD

**Issue by AndreR** [unknown-horizons/unknown-horizons#1256]
A new music system should be implemented, which can adjust the music to the current ingame mood. This affects not just the selection of the music file, that should be played next, but also how the current music sounds like.

I discussed with Novatlan about that topic and we developed a completely new music system, which is based on dynamic audio tracks, which can be modified from within the game.

Every track is based on at least one ogg file and one yaml description. It contains a list of files, which are allocated to a specific ID. This block is followed by a timeline, which contains various tracks. The tracks consist of a list of conditions and a list of files, which should be played at a defined time, using the IDs from above.

``` yaml
Files:
- Main1: uh_battle1_mid_1.ogg
- Main2: uh_battle1_mid_2.ogg
- Main3: uh_battle1_mid_3.ogg
- Main4: uh_battle1_mid_4.ogg
- Main5: uh_battle1_mid_5.ogg

Timeline:
- Basetrack:
  - Conditions:
    - min mood: 10
    - max mood: 100
  - Patterns:
    - From: 00:00:000
      File: Main1
    - From: 00:06:802
      File: Main2
    - From: 00:20:406
      File: Main3
    - From: 00:34:010
      File: Main4
    - From: 00:47:614
      File: Main5
```

The min_mood and max_mood conditions are just an example. Ingame events like a ongoing sea fight should trigger those tracks and turn them on and off. This must happen by fading them in or out. Crossfades between two tracks should be implied. It could also be possible to define a track without any conditions, which means, that it's played all the time.

Conditions could be for example:
- Ongoing fights
- The chance of winning or loosing a war
- The current popularity within the population
- [ . . . ]

A prototype written in VB.net and DirectX is attached to this ticket.

**Attachment**: [MusikTest_Final.7z](http://up.unknown-horizons.org/f/?id=225&n=MusikTest_Final.7z)
##
