### ISSUE TITLE
Scenario message action has no effect.

### ISSUE THREAD

**Issue by DanielStephens** [unknown-horizons/unknown-horizons#1840]
Currently the message action seems to be completely ignored, no errors are produced when using it but no new message is shown.

A test scenario can be found here: http://bpaste.net/show/43478/

**Comment by squiddy** [comment]
Seems to work fine.

```yaml
events:
- # Show a message after starting the game (how to move)
  actions:
   - type: message
     arguments: [None, 'Errichtet ein Kontor an der Küste']
  conditions:
   - type: game_started
     arguments: []

metadata:
  author: Me
  description: Test
  difficulty: Einführung
  locale: de
  mapfile: development.sqlite
  original: content/scenarios/test_de.yaml
  translation_status: 188 translated messages.
```

Unfortunately the link from the issue is dead, so I can't compare. None of the scenarios that we ship is using that action, so I'm closing this.
