### ISSUE TITLE
configure buildability via components

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#1877]
It would be a nice feature to be able to configure the buildability for builings in their object files via an own component. This ticket should be an first draft, how such a system could look like.

In Unknown Horizons are multiple layers, the buildability depends on all? of these layers.

This layers are:
1.  GROUND: The ground tiles itself
2.  STUFF(everything thats handled like a building):  buildings, tress, paths, deposits, mountains, ruined tents ...
...

Some default values have to be created, for example should it be possible to build upon paths and trees per default if you didn't deny it explicitly for this object.
But if you create an Allow, the default values are trashed and you have to rewrite them if you only want to add a third like mountains.
The system should be highly configurable. but could be create some overheat in the object files, maybe this can be reduced by good default values?

List of possibilities:
Water (should be disabled by default, but possible to allow (Usecase could be the pier))
Water_fresh
Water_saline
Coast
Coast_fresh
Coast_saline
Desert
... much more

``` yaml
# Example 1
# Buildable everywhere except in the desert.
- BuildableComponent:
     - GROUND:
           Deny: [Desert]
     - STUFF:
           Deny: [Paths]

# Example 2:
# Only buildable at fresh and saline water coasts.
- BuildableComponent:
     - GROUND:
           Allow: [Coast_fresh, Coast_saline]

# Example 3:
# In the near of building type XYZ. Usecase could be the pier.
- BuildableComponent;
     - GROUND:
           NearOf: [Harbour]

# Example 3:
# Usecase claypit
- BuildableComponent;
     - STUFF:
           Allow: [ClayDepsoit]
```
