### ISSUE TITLE
More readable markup for InventoryOverlayComponent overlays

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2141]
This would need a new subtype of action sets, so that the directories specifying resource amount (01..05, 01..12) are not interpreted as rotation by our loaders.
Overall it should reduce noise greatly for the yaml files.
Drawbacks: More complex loader code, changing game data requires moving (binary) image files, implicit `null` overlay for amount 0.

Desired:

``` yaml
      as_lumberjack_barrack0:
        idle:
          RES.BOARDS: planks
          RES.TREES: logs
```

with 

```
|-- idle
|   |-- 135
|   |   `-- 0.png
|   |-- 225
|   |   `-- 0.png
|   |-- 315
|   |   `-- 0.png
|   `-- 45
|       `-- 0.png
|-- logs
|   |-- 01
|   |   |-- 135
|   |   |   `-- 0.png
|   |   |-- 225
|   |   |   `-- 0.png
|   |   |-- 315
|   |   |   `-- 0.png
|   |   `-- 45
|   |        `-- 0.png
|   |-- 02
...
|-- trees
...
```

Right now:

``` yaml
      as_lumberjack_barrack0:
        idle:
          RES.BOARDS:
            - [0, null]
            - [1, planks_01]
            - [2, planks_02]
            - [3, planks_03]
            - [4, planks_04]
            - [5, planks_05]
            - [6, planks_06]
            - [7, planks_07]
            - [8, planks_08]
            - [9, planks_10]
            - [10, planks_12]
          RES.TREES:
            - [0, null]
            - [1, logs_01]
            - [3, logs_02]
            - [5, logs_03]
            - [7, logs_04]
            - [9, logs_05]
```

where

```
content/gfx/buildings/pioneers/lumberjack_barrack/as_lumberjack_barrack0/
|-- idle
|   |-- 135
|   |   `-- 0.png
|   |-- 225
|   |   `-- 0.png
|   |-- 315
|   |   `-- 0.png
|   `-- 45
|       `-- 0.png
|-- logs_01
|   |-- 135
|   |   `-- 0.png
|   |-- 225
|   |   `-- 0.png
|   |-- 315
|   |   `-- 0.png
|   `-- 45
|       `-- 0.png
...
|-- logs_05
|   |-- 135
|   |   `-- 0.png
|   |-- 225
|   |   `-- 0.png
|   |-- 315
|   |   `-- 0.png
|   `-- 45
|       `-- 0.png
|-- planks_01
|   |-- 135
|   |   `-- 0.png
|   |-- 225
|   |   `-- 0.png
|   |-- 315
|   |   `-- 0.png
|   `-- 45
|       `-- 0.png
...
`-- planks_12
    |-- 135
    |   `-- 0.png
    |-- 225
    |   `-- 0.png
    |-- 315
    |   `-- 0.png
    `-- 45
        `-- 0.png
```
